### ISSUE TITLE
Problem with - gfortran-ARM-11.0-BigSur.pkg

### ISSUE THREAD

**Issue by righthalfplane** [fxcoudert/gfortran-for-macOS#26] opened 2021-05-17 01:22 UTC
I installed - gfortran-ARM-11.0-BigSur.pkg - on my new Mackbook pro - M1.

Everthing seemed go ok except when I try to compile something, I get -

[dale:~/utlib] dir% gfortran -o test test.f
ld: library not found for -lm
collect2: error: ld returned 1 exit status
[dale:~/utlib] dir% gfortran --version
GNU Fortran (GCC) 11.0.0 20201205 (experimental)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

macOS Big Sur - version 11.3.1.

I have "xCode version 12.5" installed and the C compiler works Ok.

[dale:~/utlib] dir% cc -o test2 test2.c
[dale:~/utlib] dir% test2
Hello 0.049979

Something is generating a  -lm and that is causing the failure. It is not needed - with another other program I removed the -lm from the script and the error went alway and the program worked, but here I cannot find what is generating it.

My real program has 5 parts, all of the parts compiled Ok - it did not fail until the link step.

**Comment by virk** [comment] 2021-08-26 17:14
Is this topic solved? I just experienced a similar error with hpc.sourgeforge.net-Fortran and M1 Macbook Pro with Big Sur.

3 hours later: I solved my (similar) problem by installing the "Command Line Tools for Xcode 12.5.1" from https://developer.apple.com/download/all/

xcode "told" me in its /Preferences/Locations/ that the tools were already installed, but perhaps they weren't or weren't correctly or I misunderstood something (which for sure is the case :-) ) In any case gfortran now works.

**Comment by davidjohnbaker1** [comment] 2021-09-09 13:56
I also had problems at first with my M1 setup (OSx Big Sur 11.3.1) and was able to fix it all by following the steps in this comment here: https://github.com/rmacoslib/r-macos-rtools/issues/42#issuecomment-765899747

My fix was that I needed gfortran-8.2, not one of the new ones. This might be a temporary fix, but it worked for me (assuming you have xcode, R 4.X+, clear the Makevars files, then install it from source per the comment

**Comment by fxcoudert** [comment] 2021-10-15 21:14
Unclear what the issue is here, but it sounds like "installing command-line tools" is a working solution. It is documented in the package, so closing for now.

**Closed as completed by fxcoudert** 2021-10-15 21:14 UTC
